# Generated by Django 3.0.7 on 2020-06-16 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='score',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
