# Generated by Django 3.0.7 on 2020-06-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_word_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='level',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
